<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/../lib/DemoGrowthWorkspace.php';
require_login(); require_perm('dashboard');
if ($_SERVER['REQUEST_METHOD']==='POST') { csrf_verify(); $command=(string)($_POST['command']??'reset'); $r=$command==='reset'?demo_growth_install():demo_growth_command($command); flash($r['ok']?'success':'error',$r['ok']?($command==='reset'?'Demo 数据已恢复为标准场景':'Demo Loop 已推进：'.($r['state']??$command)):'Demo 操作失败：'.($r['error']??'')); header('Location: /xmp/demo-growth'); exit; }
$state=demo_growth_read(); $view=demo_growth_compare($state['data']); $m=$view['loop']['metrics'];
$sim=demo_loop_state($state['data']); $phase=$sim['loop_run']['status']??'not_started';
admin_header('Demo 陪跑');
?>
<div class="admin-layout"><?php admin_sidebar('demo-growth'); ?><div class="main">
  <div class="v-head"><div><h1>Demo 陪跑 <span class="st st-warn">隔离演示数据</span></h1><p class="v-sub">增长大脑与黄金 Loop 读取同一批画像、行为证据和模拟成交真相。用于跑通产品，不代表真实经营结果。</p></div><div class="v-actions"><form method="post"><?=csrf_field()?><input type="hidden" name="command" value="reset"><button class="btn btn-s btn-sm">一键重置 Demo</button></form></div></div>
  <div class="panel" style="margin-bottom:16px"><div class="p-body"><strong>安全边界：</strong>仅写入 <span class="mono">data/demo/</span>；不写 CDP、不打标签、不触达、不创建订单、不进入生产报表。所有身份均为 <span class="mono">DEMO-*</span>，邮箱使用保留域 <span class="mono">.example</span>。</div></div>
  <div class="kpi-grid"><div class="kpi"><div class="k-label">场景状态</div><div class="k-val" style="font-size:20px"><?=$state['installed']?'已装载':'预览中'?></div><div class="k-sub">可随时恢复标准数据</div></div><div class="kpi"><div class="k-label">共享样本</div><div class="k-val mono"><?=count($view['rows'])?></div><div class="k-sub">两套引擎同源</div></div><div class="kpi"><div class="k-label">Loop 高意向</div><div class="k-val mono"><?=$m['true_positive']?></div><div class="k-sub">可解释证据评分</div></div><div class="kpi"><div class="k-label">生产写入</div><div class="k-val mono">0</div><div class="k-sub">硬隔离</div></div></div>
  <div class="panel" style="margin-bottom:16px"><div class="p-head"><h3>完整闭环演示</h3><span class="p-sub mono">状态：<?=htmlspecialchars($phase)?></span></div><div class="p-body"><p class="text-sm text-muted">模拟 FlowRun → ActionProposal → 人工 Approval → DemoActionGateway 标签回读 → Evaluation → Memory。仅写入 Demo 文件。</p><div class="v-actions"><?php if($phase==='not_started'): ?><form method="post"><?=csrf_field()?><input type="hidden" name="command" value="start"><button class="btn btn-primary btn-sm">1. 生成待审批行动</button></form><?php elseif($phase==='awaiting_approval'): ?><form method="post"><?=csrf_field()?><input type="hidden" name="command" value="approve"><button class="btn btn-primary btn-sm">2. 模拟人工批准</button></form><?php elseif($phase==='executing'): ?><form method="post"><?=csrf_field()?><input type="hidden" name="command" value="execute"><button class="btn btn-primary btn-sm">3. 执行并回读标签</button></form><?php else: ?><span class="st st-ok">闭环已完成 · 可重置后重跑</span><?php endif; ?></div><?php if($sim): ?><div class="text-xs text-muted" style="margin-top:10px">行动：<?=htmlspecialchars($sim['action']['action']??'')?> · FlowRun：<?=htmlspecialchars($sim['flow_run']['id']??'')?> · Evaluation：<?=htmlspecialchars($sim['evaluation']['id']??'尚未产生')?></div><?php endif; ?></div></div>
  <div class="panel"><div class="p-head"><h3>增长大脑 × 黄金 Loop 并排陪跑</h3><span class="p-sub">同一证据，不同决策方式</span></div><div class="p-body"><div class="table-wrap"><table><thead><tr><th>Demo 对象</th><th>增长大脑（规则建议）</th><th>黄金 Loop（TIPS 计划）</th><th>边界</th></tr></thead><tbody>
  <?php foreach($view['rows'] as $row): $l=$row['loop']; ?><tr><td><strong><?=htmlspecialchars($row['name'])?></strong><div class="text-xs mono"><?=htmlspecialchars($row['subject_id'])?></div></td><td><?=$row['brain']?htmlspecialchars($row['brain']['action']).'<div class="text-xs text-muted">'.htmlspecialchars($row['brain']['reason']).'</div>':'<span class="text-muted">暂无强建议</span>'?></td><td><strong>意向分 <?=$l['score']?></strong><div class="text-xs text-muted"><?=$l['predicted_high_intent']?'准备“高意向”待审核行动':'继续观察，不生成行动'?></div></td><td><span class="st <?=$l['blocked_reason']?'st-danger':'st-ok'?>"><?=$l['blocked_reason']?htmlspecialchars($l['blocked_reason']):'Demo only'?></span></td></tr><?php endforeach; ?>
  </tbody></table></div></div></div>
</div></div><?php admin_footer(); ?>
