<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/../lib/AutomationSystem.php';
require_once __DIR__ . '/../lib/CanvasSystem.php';
require_once __DIR__ . '/../lib/GrowthAction.php';
require_once __DIR__ . '/../lib/GrowthSignal.php';
require_once __DIR__ . '/../lib/FlowWorkspace.php';
require_once __DIR__ . '/../lib/WorkflowLibrary.php';
require_login(); require_perm('settings');
$workspace = flow_workspace_current(trim((string)($_GET['flow'] ?? '')));
$flow = $workspace['definition']; $steps = $flow['structure']['steps'] ?? $flow['structure']['nodes'] ?? [];
$capabilities=array_values(array_filter(array_map('workflow_library_capability',$workspace['definitions']),fn($cap)=>$cap['ok']));
$statusClass = ($flow['status'] ?? '') === 'active' ? 'st-ok' : 'st-faint';
$baselineMetrics = ['sample_size'=>120,'conversion_rate'=>0.11,'cost'=>10.5,'wrong_contact_rate'=>0.08];
$candidateMetrics = ['sample_size'=>140,'conversion_rate'=>($flow['risk_level'] ?? 'medium')==='low'?0.19:0.14,'cost'=>($flow['risk_level'] ?? 'medium')==='low'?8.9:9.8,'wrong_contact_rate'=>($flow['risk_level'] ?? 'medium')==='low'?0.04:0.06];
$compare = workflow_library_compare($baselineMetrics, $candidateMetrics);
$compareStats = ['open_wins'=>($compare['delta']['conversion_rate']>=0),'actual_delta'=>100*$compare['delta']['conversion_rate'],'cost_improved'=>($compare['delta']['cost']<=0),'risk_improved'=>($compare['delta']['wrong_contact_rate']<=0)];
admin_header('Flow 工作台');
?>
<div class="admin-layout"><?php admin_sidebar('flow-workspace'); ?><div class="main">
  <div class="v-head"><div><h1>Flow 工作台 <span class="st st-warn">只读聚合</span></h1><p class="v-sub">在一个业务视图中查看定义、运行、关联审批与结果。配置和执行仍由原有 Flow 页面负责。</p></div><div class="v-actions"><a class="btn btn-s btn-sm" href="/xmp/loop-workspace">查看 Loop 工作台</a><?php if($flow): ?><a class="btn btn-s btn-sm" href="/xmp/<?=($flow['source_type']==='canvas'?'canvas':'automation')?>">编辑原 Flow</a><?php endif; ?></div></div>
  <div class="panel" style="margin-bottom:16px"><div class="p-body" style="display:flex;gap:12px;align-items:end;flex-wrap:wrap"><form method="get" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><label style="min-width:280px;flex:1"><span class="text-xs text-muted">选择现有 Flow</span><select name="flow" onchange="this.form.submit()" style="width:100%;margin-top:5px"><?php foreach($workspace['definitions'] as $item): ?><option value="<?=htmlspecialchars($item['id'])?>" <?=$item['id']===$workspace['selected_id']?'selected':''?>><?=htmlspecialchars($item['name'] ?: $item['id'])?> · <?=htmlspecialchars($item['source_type'])?></option><?php endforeach; ?></select></label><noscript><button class="btn btn-primary btn-sm">查看</button></noscript></form><span class="text-xs text-muted">共 <?=$workspace['counts']['definitions']?> 条 Flow；此页没有保存、启停或执行按钮。</span></div></div>
  <?php if(!$flow): ?><div class="of-empty">尚无可展示的 Flow。请先在营销自动化或画布中创建一条流程。</div><?php else: ?>
  <div class="kpi-grid"><div class="kpi"><div class="k-label">定义状态</div><div class="k-val" style="font-size:20px"><span class="st <?=$statusClass?>"><?=htmlspecialchars($flow['status'])?></span></div><div class="k-sub"><?=htmlspecialchars($flow['source_type'])?> · v<?=$flow['version']?></div></div><div class="kpi"><div class="k-label">结构步骤</div><div class="k-val mono"><?=count($steps)?></div><div class="k-sub">触发：<?=htmlspecialchars($flow['trigger'] ?: '未声明')?></div></div><div class="kpi"><div class="k-label">结构化运行</div><div class="k-val mono"><?=$workspace['counts']['runs']?></div><div class="k-sub">只计可验证 FlowRun</div></div><div class="kpi"><div class="k-label">已关联结果</div><div class="k-val mono"><?=$workspace['counts']['evaluated']?></div><div class="k-sub">审批 → 执行 → 评估</div></div></div>
  <div class="panel" style="margin-bottom:16px"><div class="p-head"><h3>Flow 定义</h3><span class="p-sub mono"><?=htmlspecialchars($flow['id'])?> · <?=htmlspecialchars(substr($flow['structure_hash'],0,12))?></span></div><div class="p-body"><div class="text-sm text-muted" style="margin-bottom:10px">风险等级：<?=htmlspecialchars($flow['risk_level'])?> · 更新：<?=htmlspecialchars($flow['updated_at'] ?: '未记录')?></div><div style="display:flex;gap:8px;flex-wrap:wrap"><?php foreach($steps as $i=>$step): ?><span class="st st-faint"><?=($i+1)?> · <?=htmlspecialchars((string)($step['action'] ?? $step['type'] ?? '步骤'))?></span><?php endforeach; ?></div></div></div>
  <div class="panel" style="margin-bottom:16px"><div class="p-head"><h3>最近运行</h3><span class="p-sub mono">STRUCTURED EVIDENCE ONLY</span></div><div class="p-body"><?php if(!$workspace['runs']): ?><div class="of-empty" style="border:0">还没有可归属到此 Flow 的结构化运行记录。旧日志仍保留原样，但因缺少稳定运行边界不会被误计为成功或失败。</div><?php endif; ?><?php foreach(array_slice($workspace['runs'],0,10) as $run): ?><div class="todo-row"><span class="t-b"><span class="t-t"><?=htmlspecialchars($run['trigger'])?></span><span class="t-d mono"><?=htmlspecialchars($run['id'])?> · <?=htmlspecialchars($run['created_at'])?></span></span><span class="st <?=($run['status']==='succeeded'?'st-ok':'st-faint')?>"><?=htmlspecialchars($run['status'])?></span></div><?php endforeach; ?></div></div>
  <div class="panel" style="margin-bottom:16px"><div class="p-head"><h3>可调用能力</h3><span class="p-sub mono">FLOW AS SKILL · DECLARATION ONLY</span></div><div class="p-body"><?php foreach($capabilities as $cap): ?><div class="todo-row"><span class="t-b"><span class="t-t"><?=htmlspecialchars($cap['name'])?></span><span class="t-d">风险 <?=htmlspecialchars($cap['risk_level'])?> · 权限 <?=htmlspecialchars(implode(', ',$cap['permissions'])?:'无')?></span></span><span class="st <?=($cap['status']==='available'?'st-ok':'st-faint')?>"><?=htmlspecialchars($cap['status'])?></span></div><?php endforeach; ?><p class="text-xs text-muted" style="margin-top:14px">这是供 Loop 选择的稳定能力声明；当前没有在这里直接调用 Flow 的生产执行入口。</p></div></div>
  <div class="panel"><div class="p-head"><h3>关联行动与结果</h3><span class="p-sub mono">APPROVAL → EXECUTION → EVALUATION</span></div><div class="p-body"><?php if(!$workspace['chains']): ?><div class="of-empty" style="border:0">暂无可由此 FlowRun 追溯的行动链。此处不会显示无运行关联的全局建议。</div><?php endif; ?><?php foreach($workspace['chains'] as $chain): $a=$chain['action'];$ap=$chain['approval'];$ex=$chain['execution'];$ev=$chain['evaluation']; ?><div class="todo-row" style="align-items:flex-start"><span class="t-b"><span class="t-t"><?=htmlspecialchars($a['action'] ?? $ex['action_id'])?></span><span class="t-d">审批：<?=htmlspecialchars($ap['decision'] ?? '未投影')?> · 执行：<?=htmlspecialchars($ex['status'] ?? '未投影')?> · 结果：<?=htmlspecialchars($ev ? ($ev['metric'].' Δ'.$ev['delta']) : '尚未评估')?></span></span><span class="st st-faint">只读</span></div><?php endforeach; ?><p class="text-xs text-muted" style="margin-top:14px">行动审批中心仍是唯一审计入口；生产执行保持关闭。后续 Loop 只会复用这些对象，不复制 Flow 数据。</p></div></div>
  <div class="panel"><div class="p-head"><h3>版本对比评估</h3><span class="p-sub mono">BASELINE vs CANDIDATE · SYNTHETIC</span></div><div class="p-body"><div class="table-wrap"><table><thead><tr><th>指标</th><th>基线</th><th>候选</th><th>Δ</th><th>结论</th></tr></thead><tbody><tr><td>样本量</td><td><?=htmlspecialchars($compare['baseline']['sample_size'])?></td><td><?=htmlspecialchars($compare['candidate']['sample_size'])?></td><td><?=htmlspecialchars($compare['delta']['sample_size'])?></td><td class="text-muted">—</td></tr><tr><td>转化率</td><td><?=number_format(100*$compare['baseline']['conversion_rate'],1)?>%</td><td><?=number_format(100*$compare['candidate']['conversion_rate'],1)?>%</td><td class="<?=$compare['delta']['conversion_rate']>=0?'st-ok':'st-danger'?>"><?=number_format(100*$compare['delta']['conversion_rate'],1)?>pp</td><td><?=$compareStats['open_wins']?'提升':'下降'?></td></tr><tr><td>成本</td><td><?=htmlspecialchars($compare['baseline']['cost'])?></td><td><?=htmlspecialchars($compare['candidate']['cost'])?></td><td class="<?=$compare['delta']['cost']<=0?'st-ok':'st-danger'?>"><?=htmlspecialchars($compare['delta']['cost'])?></td><td><?=$compareStats['cost_improved']?'降低':'上升'?></td></tr><tr><td>错误触达率</td><td><?=number_format(100*$compare['baseline']['wrong_contact_rate'],1)?>%</td><td><?=number_format(100*$compare['candidate']['wrong_contact_rate'],1)?>%</td><td class="<?=$compare['delta']['wrong_contact_rate']<=0?'st-ok':'st-danger'?>"><?=number_format(100*$compare['delta']['wrong_contact_rate'],1)?>pp</td><td><?=$compareStats['risk_improved']?'降低':'升高'?></td></tr></tbody></table></div><div class="v-actions" style="margin-top:12px"><span class="st <?=$compare['candidate_better']?'st-ok':'st-warn'?>"><?=$compare['candidate_better']?'候选优于基线（业务+风险均改进）':'未全部达标'?></span><span class="text-xs text-muted">沙盘合成指标，用于演示 <span class="mono">workflow_library_compare</span>；不读取真实经营数据。</span></div></div></div>
  <?php endif; ?>
</div></div><?php admin_footer(); ?>
